# Generated by Django 3.1.4 on 2020-12-11 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20201211_1438'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='likes',
            new_name='liked',
        ),
    ]
